# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\Utilisateur:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
    #    in_memory:
    #        memory: ~
        our_db_provider:
            entity:
                class: AppBundle:Utilisateur
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager 
                default_target_path: user_homepage
            logout:
                path:   /logout
                target: homepage
                
        #secured_area:
        #    pattern: ^/
        #    anonymous: ~

        
    
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_PARTENAIRE]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/part, roles: ROLE_PARTENAIRE }
        - { path: ^/admin, roles: ROLE_ADMIN }